# Generated by Django 3.2.3 on 2022-03-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner',
        ),
    ]
