# Generated by Django 3.2.3 on 2022-03-28 21:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.user_directory_path_banner, verbose_name='Banner'),
        ),
    ]
