# Generated by Django 3.2.10 on 2021-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('student_dob', models.CharField(max_length=50)),
                ('student_year', models.CharField(max_length=50)),
                ('student_school', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_dob', models.CharField(max_length=50)),
                ('teacher_year', models.CharField(max_length=50)),
                ('teacher_school', models.CharField(max_length=50)),
            ],
        ),
    ]
