# Generated by Django 3.2.9 on 2021-12-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_category_question_quizzes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name': 'Student Info', 'verbose_name_plural': 'Student Information'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
