# Generated by Django 3.2.9 on 2021-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211215_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_correct',
            new_name='is_right',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quizzes',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quizType',
            new_name='technique',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_input',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default='String', max_length=255, verbose_name='Answer Text'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='String', max_length=255),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255, verbose_name='Quiz Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Fundamental'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=0, verbose_name='Difficulty'),
        ),
    ]
