# Generated by Django 3.0.2 on 2022-03-11 13:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
