# Generated by Django 3.2.10 on 2022-02-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('hours', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='module_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
