# Generated by Django 3.0.2 on 2022-03-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('module', '0002_auto_20220307_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(to='page.Page'),
        ),
    ]
