# Generated by Django 3.0.2 on 2022-03-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_module_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pages',
        ),
    ]
